### ISSUE TITLE
[BUG] I can't reproduce the instance model

### ISSUE THREAD

**Issue by SHIJIE0313** [salesforce/Merlion#102]
**Describe the bug**
I can't reproduce the instance model

**To Reproduce**
The problem is on the ts-datasets installation，

if i use 
`pip install -e ../Merlion/ts-datasets/`
when i run the program the error is can not find ts-datasets，

if i use
`pip install  ../Merlion/ts-datasets/`
when i run the program the error is [Errno 2] No such file or directory: '/usr/local/lib/python3.8/data/M4/M4-info.csv'

**Expected behavior**
what should i do to solve this problem

**Desktop (please complete the following information):**
 - OS: linux
 - Merlion Version [1.2.0]

**Comment by SHIJIE0313** [comment]
I try to use this way to solve this problem,but lose.
```
!git clone https://github.com/salesforce/Merlion.git
!pip install  Merlion/ts_datasets/
```

**Comment by aadyotb** [comment]
You need to do
```
!git clone https://github.com/salesforce/Merlion.git
!pip install -e Merlion/ts_datasets/
```
The `-e` is important; otherwise you will need to manually specify the directory at which each dataset is stored. Also make sure to call this from the directory where you can find `Merlion`. Otherwise `pip` can get confused.

**Comment by SHIJIE0313** [comment]
> 

This problem has been solved, because I tried to access github in China, due to some reasons, the dataset cannot be downloaded, and it needs to be downloaded manually

**Comment by lambdong** [comment]
> > 
> 
> 这个问题已经解决，因为我尝试在国内访问github，由于某些原因，无法下载数据集，需要手动下载

您好，非常感谢您提出的问题，我也遇到类似的问题，但是不知在哪手动下载，非常希望能得到您的回复，来自一位刚接触这方面小白的提问。
