### ISSUE TITLE
[Help] Not getting a proper forecast using DefaultForecaster

### ISSUE THREAD

**Issue by bkowshik** [salesforce/Merlion#105]
Following the tutorial, I tried to get some forecasts on some quarter hourly datasets. Split the dataset into the `train` and `test` parts, training the model on the `train` dataset and getting model predictions on the `test` dataset.

<img width="1595" alt="Screenshot 2022-06-07 at 8 51 37 PM" src="https://user-images.githubusercontent.com/2899501/172643176-4c0461de-53e7-46b4-8b45-4d4e50c912f9.png">

But, from a predictions point of view, I get something like this. There is a forecast for the first few quarter hours but later things drop and flatten at a value. I don't understand what is causing this and how do I get a proper forecast.

<img width="381" alt="Screenshot 2022-06-07 at 8 51 53 PM" src="https://user-images.githubusercontent.com/2899501/172643344-c3bd4b7a-1f40-4cbc-9cdc-e64bf18dbbf2.png">

The code snippet is straight from the [tutorial](https://github.com/salesforce/Merlion/blob/main/examples/forecast/0_ForecastIntro.ipynb). Any help will be appreciated. 🙏

```python
from merlion.models.defaults import DefaultForecasterConfig, DefaultForecaster

model = DefaultForecaster(DefaultForecasterConfig())
model.train(train_data=dataset_train)

predictions, errors = model.forecast(time_stamps=dataset_test.time_stamps)
```

**Comment by aadyotb** [comment]
Ultimately the performance of the model is data-dependent. The default models are meant to give a good starting point, but they may not be suitable for all datasets. From looking at this time series, the `AutoProphet` model may be a better fit instead.

**Comment by bkowshik** [comment]
Thank you @aadyotb Closing this ticket for now.
