### ISSUE TITLE
[BUG] Anomaly Detection example doesn't work

### ISSUE THREAD

**Issue by bayd** [salesforce/Merlion#111]
**Describe the bug**
The example for Anomaly detection doesn't work for me. 

**To Reproduce**
I have istalled Merlion and data as was explained in the instruction. But can't run the second cell in Jupyter notebook, see the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/26165213/176377546-87ac318d-3ec4-4440-82fd-617a529ce1a3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Merlion Version [e.g. 1.2.3]

**Additional context**

**Comment by aadyotb** [comment]
I'll need a full stack trace, but realistically it looks like you don't have Java installed.
