### ISSUE TITLE
[FEATURE REQUEST] Load from zipfile

### ISSUE THREAD

**Issue by jorgegarcia197** [salesforce/Merlion#132]
**Is your feature request related to a problem? Please describe.**
I am trying to create a solution that is serverless and load a model from a cloud storage, so an easy way to upload the config + binary data could be a .zip or a .tar object. Currently i am trying to upload it separately into a folder but it takes two trips and two downloads before the loading, adding latency to my system

**Describe the solution you'd like**
To be able to load from the ModelFactory from a file that is compressed assuming it contains both of the files (config + binary data) 

**Describe alternatives you've considered**
As I states on the first question, I am currently considering to download them individually but it is not optimal 

Thank you in advance! And I really hope you can help me out because I really think is a powerful library.

**Comment by aadyotb** [comment]
Thanks for the suggestion. You actually are able to save/load the model to/from a single binary file as follows:
```python
# Save
with open("model.bin", "wb") as f:
    dill.dump(model.to_bytes(), f)

# Load
with open("model.bin", "rb") as f:
   model = ModelFactory.load_bytes(dill.load(f))
```
Let me know if this addresses your concerns.

**Comment by jorgegarcia197** [comment]
Hi! just following up on this issue

This snippet did solve my issue! 

Thank you for your fast response! I will be closing this issue
