### ISSUE TITLE
[BUG] Unable to use merlion dashboard - missing release?

### ISSUE THREAD

**Issue by anton164** [salesforce/Merlion#140]
**Describe the bug**
I'm unable to install the Merlion dashboard - it seems that it wasn't released. Last release is 1.3.1 before the dashboard was merged. It might be that you don't intend to release it yet, but in that case the README on the `main` branch is confusing.

**To Reproduce**
```
pip install "salesforce-merlion[dashboard]"
python -m merlion.dashboard            
> python: No module named merlion.dashboard
```

**Workaround:**
Install from source

**Comment by aadyotb** [comment]
Hey, sorry for the confusion. We're planning to release this with v2.0.0, which is currently in the final stages of development.

**Comment by aadyotb** [comment]
Closing this issue due to the release of Merlion v2.0.0, which addresses the problem.
