### ISSUE TITLE
How to install ts_datasets to COLAB?

### ISSUE THREAD

**Issue by treexterr** [salesforce/Merlion#15]
Hi.
Tried to install with:
pip install ts_datasets
pip install ts-datasets

What i do wrong?

**Comment by paulkass** [comment]
>To install the data loading package ts_datasets, clone this repo, navigate to its root directory, and call pip install -e ts_datasets/. This package must be installed in editable mode (i.e. with the -e flag) if you don't want to manually specify the root directory of every dataset when initializing its data loader.

so I would imagine in a notebook, you would call the command to clone the repo and then run `pip install -e ts_datasets/` to  install the package.

**Comment by treexterr** [comment]
pip install git+https://github.com/salesforce/Merlion.git
pip install -e ts_datasets/

output: 
ERROR: ts_datasets/ is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

Do you have valid colab notebook?

**Comment by paulkass** [comment]
Try including this in your collab:

```
!pip install salesforce-merlion
!git clone https://github.com/salesforce/Merlion.git
!pip install -e Merlion/ts_datasets/
```

**Comment by Jia-py** [comment]
> > Try including this in your collab:
> > ```
> > !pip install salesforce-merlion
> > !git clone https://github.com/salesforce/Merlion.git
> > !pip install -e Merlion/ts_datasets/
> > ```
> 
> when try install, see next:
> 
> > Installing collected packages: ts-datasets
> > Running setup.py develop for ts-datasets
> > Successfully installed ts-datasets-0.1.0
> 
> but after
> 
> > from ts_datasets.anomaly import NAB
> 
> > ModuleNotFoundError: No module named 'ts_datasets'

I find that when I remove the -e, it works.
