### ISSUE TITLE
[FEATURE REQUEST] Update/Forecast/Update example for MoE

### ISSUE THREAD

**Issue by slyons** [salesforce/Merlion#17]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out if it's possible to update the MoE example with new data as it comes in or if the model has to be rebuilt every time.

**Describe the solution you'd like**
An example similar to the MSES example with the update/prediction loop. 

**Describe alternatives you've considered**
The MSES model didn't even come close to creating something predictable, but MoE seemed to do a decent job.

**Comment by paulkass** [comment]
MSES so far is the only forecaster model that supports the `update` method unfortunately, so it wouldn't be possible to create an example of MoE using the same features at the moment. However we are considering adding a "streaming" feature to our forecasting models to enable the update/prediction loops for our forecasting models.
