### ISSUE TITLE
GPU utilization

### ISSUE THREAD

**Issue by SM-93** [salesforce/Merlion#33]
Hi, 
is it possible to train the model using GPU ? 
I don't see where we can specify the gpu parameter, for example when wanting to use AutoML module. 

Thanks

**Comment by aadyotb** [comment]
Most of the deep learning models support GPU utilization (they should have a `cuda` or `gpu` parameter in their config objects). However, many of the classical models (e.g. SARIMA) only have CPU implementations.

**Comment by SM-93** [comment]
Appreciate the quick answer. 
I am asking this since I am trying to solve multivariate problem with 9 features and around 15k observations. 
That is why I asked if it is possible to use gpu to speed up the process :)
