### ISSUE TITLE
[BUG]delay value when creating a TSADEvaluator

### ISSUE THREAD

**Issue by jeicy07** [salesforce/Merlion#37]
**Describe the bug**
In **benchmark_anomaly.py line 307**:
`delay = post_rule_train_config["max_early_sec"]`
Should it be `delay = post_rule_train_config["max_delay_sec"]` cuz post_rule_train_config is updated in `get_model() ` at  line 235 where `d.update({"max_early_sec": dataset.max_lead_sec, "max_delay_sec": dataset.max_lag_sec})`

**Comment by aadyotb** [comment]
Thanks for the catch! Addressed in #38.
