### ISSUE TITLE
[BUG] Can't pass holiday config to Prophet model

### ISSUE THREAD

**Issue by YN-Liang** [salesforce/Merlion#49]
**Describe the bug**
when setting up the holidays config in ProphetConfig and passing it to Prophet model:
ValueError: holidays must be a DataFrame with "ds" and "holiday" columns.
holidays is pd.dataframe, but after wrapping, it becomes dict;
**To Reproduce**
config2 = ProphetConfig(max_forecast_steps=None, transform=Identity(), holidays=holidays)
model2  = Prophet(config2)

**Expected behavior**

**Screenshots**
![截屏2021-12-21 上午11 37 55](https://user-images.githubusercontent.com/29485141/146866917-12288846-c7f2-44be-9a3d-30ec2cc518c6.png)

**Desktop (please complete the following information):**
 - OS: Macbook
 - Merlion 1.1.0, 1.0.2

**Additional context**

**Comment by aadyotb** [comment]
Thanks for surfacing this issue. This is fixed in #59.
