### ISSUE TITLE
[FEATURE REQUEST]More light-weight version

### ISSUE THREAD

**Issue by yangyang919** [salesforce/Merlion#64]
**Is your feature request related to a problem? Please describe.**
Is there a way to install a simplified version of Merlion? We are trying put Merlion into a docker image. But when building the image, we found out that Merlion depends on torch and prophet, which has very large size (around 5GB). If we are not using models related to torch and prophet, can we have a more light-weight version?

**Comment by aadyotb** [comment]
Yes. As of v1.1.1, the base install of Merlion does not include torch and prophet. These are listed as optional dependencies.
