### ISSUE TITLE
[FEATURE REQUEST] business working days

### ISSUE THREAD

**Issue by GuidoBorrelli** [salesforce/Merlion#67]
**Is your feature request related to a problem? Please describe.**
When I predict one month ahead with a daily time series of just business working days I need to make a hack to computer the parameters `max_forecast_steps`

**Describe the solution you'd like**
max_forecast_steps should work taking into account only business working days too or there should be an option to "equalize" indexes regardless of the time interval, namely dropping the time value.

**Describe alternatives you've considered**
Drop the timeindex from the pandas series

**Additional context**

**Comment by aadyotb** [comment]
You can set `max_forecast_steps` to be larger than the largest value you're expecting. So if you want to forecast 1 month in advance and have daily data, you could set `max_forecast_steps=35`.

In terms of supporting a "business days only" granularity, this is already supported for daily data, and it is called "B". The full list is in the `pandas` documentation [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases). However, these will only be inferred accurately if there are no missing time stamps; in other cases, you will have to specify the frequency manually, e.g. by passing `TemporalResample(granularity="B")` as the `transform` parameter of a model. For example:

```python
import pandas as pd
import numpy as np

from merlion.transform.resample import TemporalResample
from merlion.utils import TimeSeries

# Create a time series with data sampled once per business day (using pd.bdate_range)
n = 35
df = pd.DataFrame(np.arange(n), index=pd.bdate_range(start=0, periods=n))
ts = TimeSeries.from_pd(df)

resample = TemporalResample()
resample.train(ts)
print(resample)
```

You can verify that the trained `resample` transform will look as follows:
```
TemporalResample(
    aggregation_policy=Mean,
    granularity=B,
    missing_value_policy=Interpolate,
    origin=0.0,
    remove_non_overlapping=True,
    trainable_granularity=True)
```

Note that this will also work if you directly specify `TemporalResample(granularity="B")`.
