### ISSUE TITLE
[BUG] Calculating ForecastMetric for multivariate forecasts

### ISSUE THREAD

**Issue by darinkist** [salesforce/Merlion#73]
Hi I am facing an assertion error when calculating a forecast metric for a prediction running multivariate forecasts:

```
from merlion.evaluate.forecast import ForecastMetric

ForecastMetric.RMSE.value(ground_truth=test_multi, 
                          predict=forecast, 
                          insample=False)
```

> assert self.predict.dim == self.ground_truth.dim == 1

Since the forecast has only one dimension (my predicted sales) and the test_multi set has multiple ones (sales, store, etc.).

So I thought I could fix the problem by providing the function only the single sales column/series:

```
from merlion.evaluate.forecast import ForecastMetric

ForecastMetric.RMSE.value(ground_truth=test_multi.univariates["sales"], 
                          predict=forecast, 
                          insample=False)
```

However then I run into the following error:

> > ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-103-3fa79ece8e4c> in <module>
>       2 from merlion.evaluate.forecast import ForecastMetric
>       3 
> ----> 4 ForecastMetric.RMSE.value(ground_truth=test_multi.univariates["sales"], 
>       5                           predict=forecast,
>       6                           insample=False)
> 
> ~/opt/miniconda3/lib/python3.9/site-packages/merlion/evaluate/forecast.py in accumulate_forecast_score(ground_truth, predict, insample, periodicity, ub, lb, metric)
>     197     metric=None,
>     198 ) -> Union[ForecastScoreAccumulator, float]:
> --> 199     acc = ForecastScoreAccumulator(
>     200         ground_truth=ground_truth, predict=predict, insample=insample, periodicity=periodicity, ub=ub, lb=lb
>     201     )
> 
> ~/opt/miniconda3/lib/python3.9/site-packages/merlion/evaluate/forecast.py in __init__(self, ground_truth, predict, insample, periodicity, ub, lb)
>      51         """
>      52         t0, tf = predict.t0, predict.tf
> ---> 53         ground_truth = ground_truth.window(t0, tf, include_tf=True).align()
>      54         self.ground_truth = ground_truth
>      55         self.predict = predict.align(reference=ground_truth.time_stamps)
> 
> TypeError: align() missing 1 required positional argument: 'other'

A possible workaround would be to create a new TimeSeries object with only one dimension (sales). However, it would be cool to have a more handy solution.

What do you think?

**Comment by aadyotb** [comment]
Thanks for bringing this up. I've created PR #74 which implicitly converts a `UnivariateTimeSeries` to `TimeSeries` when attempting to compute an evaluation metric.

**Comment by aadyotb** [comment]
Closing since #74 resolves the issue.
