### ISSUE TITLE
[FEATURE REQUEST]Can we loose the requirement on numpy library 

### ISSUE THREAD

**Issue by yangyang919** [salesforce/Merlion#77]
**Is your feature request related to a problem? Please describe.**
In our ML pipeline, there are library version conflict for **numpy**:
https://github.com/kserve/kserve/pull/8 93.26 The conflict is caused by:
https://github.com/kserve/kserve/pull/8 93.26 The user requested numpy>=1.15.4
https://github.com/kserve/kserve/pull/8 93.26 cmdstanpy 0.9.68 depends on numpy>=1.15
https://github.com/kserve/kserve/pull/8 93.26 pystan 2.19.1.1 depends on numpy>=1.7
https://github.com/kserve/kserve/pull/8 93.26 matplotlib 2.0.0 depends on numpy>=1.7.1
https://github.com/kserve/kserve/pull/8 93.26 kserve 0.8.0rc0 depends on numpy~=1.19.2
https://github.com/kserve/kserve/pull/8 93.26 scikit-learn 1.0.1 depends on numpy>=1.14.6
https://github.com/kserve/kserve/pull/8 93.26 salesforce-merlion 1.1.1 depends on numpy>=1.21

Can we make numpy version requirement a bit loose, like >=1.8, etc , so that there are less chances to meet version conflict issue.

**Comment by aadyotb** [comment]
We've encountered backwards compatibility issues with older versions of numpy, so we cannot loosen this requirement.
