### ISSUE TITLE
Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

### ISSUE THREAD

**Issue by javmarina** [salesforce/Merlion#8]
When a TimeSeries is created, no matter the original DataFrame or Series index, it is recognized as 'Index', which is not valid when calling model.train().

Code to reproduce (adapted from examples):

```
from merlion.models.defaults import DefaultForecaster, DefaultForecasterConfig
from merlion.utils import TimeSeries, UnivariateTimeSeries
import pandas as pd

df = pd.DataFrame([[1632428144486, 2], [1632428160612, 6]], columns=["Time", "Value"])
df["Time"] = pd.to_datetime(df["Time"], unit="ms", utc=True)
df.set_index("Time", inplace=True)
series=df["Value"]

print(series.index)
>>> DatetimeIndex(['2021-09-23 20:15:44.486000+00:00', '2021-09-23 20:16:00.612000+00:00'], dtype='datetime64[ns, UTC]', name='Time', freq=None)

time_series = TimeSeries(univariates=[UnivariateTimeSeries.from_pd(series)])
model = DefaultForecaster(DefaultForecasterConfig())
model.train(train_data=time_series)
```

As you can see, the index is indeed DatetimeIndex, but it is lost when creating the TimeSeries.

The complete error traceback is:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\javma\miniconda3\lib\site-packages\merlion\models\defaults.py", line 185, in train
    return self.model.train(train_data=train_data, train_config=train_config)
  File "C:\Users\javma\miniconda3\lib\site-packages\merlion\models\forecast\ets.py", line 106, in train
    train_data = self.train_pre_process(train_data, require_even_sampling=True, require_univariate=False)
  File "C:\Users\javma\miniconda3\lib\site-packages\merlion\models\forecast\base.py", line 140, in train_pre_process
    train_data = super().train_pre_process(train_data, require_even_sampling, require_univariate)
  File "C:\Users\javma\miniconda3\lib\site-packages\merlion\models\base.py", line 214, in train_pre_process
    train_data = self.transform(train_data)
  File "C:\Users\javma\miniconda3\lib\site-packages\merlion\transform\resample.py", line 131, in __call__
    return time_series.align(
  File "C:\Users\javma\miniconda3\lib\site-packages\merlion\utils\time_series.py", line 895, in align
    df = df.resample(granularity, origin=origin, label="right", closed="right")
  File "C:\Users\javma\miniconda3\lib\site-packages\pandas\core\frame.py", line 10351, in resample
    return super().resample(
  File "C:\Users\javma\miniconda3\lib\site-packages\pandas\core\generic.py", line 8126, in resample
    return get_resampler(
  File "C:\Users\javma\miniconda3\lib\site-packages\pandas\core\resample.py", line 1382, in get_resampler
    return tg._get_resampler(obj, kind=kind)
  File "C:\Users\javma\miniconda3\lib\site-packages\pandas\core\resample.py", line 1558, in _get_resampler
    raise TypeError(
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
```

Windows 10 21H1, Python 3.8 (miniconda), Merlion v1.0.0

**Comment by aadyotb** [comment]
Thanks for surfacing this issue. The problem is the line
```python
df["Time"] = pd.to_datetime(df["Time"], unit="ms", utc=True)
```
If one instead uses
```python
df["Time"] = pd.to_datetime(df["Time"], unit="ms")
```
the time series is created as desired. So it seems that we currently don't handle time zones correctly. Even if I correct the way the index gets created to make it a `DatetimeIndex`, there are some deeper issues with making Merlion time series work seamlessly with time zones for all the models.

For the time being, I suggest using datetimes that do not have a time zone specified.

**Comment by raizakanwal** [comment]
Converting from Daily to Monthly Data
df_btc_monthly = df_btc_price.resample('ME', on='DATE').last()

TypeError                                 Traceback (most recent call last)
Cell In[46], line 1
----> 1 df_btc_monthly = df_btc_price.resample('ME', on='DATE').last()

File ~\anaconda3\Lib\site-packages\pandas\core\generic.py:9771, in NDFrame.resample(self, rule, axis, closed, label, convention, kind, on, level, origin, offset, group_keys)
   9768 else:
   9769     convention = "start"
-> 9771 return get_resampler(
   9772     cast("Series | DataFrame", self),
   9773     freq=rule,
   9774     label=label,
   9775     closed=closed,
   9776     axis=axis,
   9777     kind=kind,
   9778     convention=convention,
   9779     key=on,
   9780     level=level,
   9781     origin=origin,
   9782     offset=offset,
   9783     group_keys=group_keys,
   9784 )

File ~\anaconda3\Lib\site-packages\pandas\core\resample.py:2050, in get_resampler(obj, kind, **kwds)
   2046 """
   2047 Create a TimeGrouper and return our resampler.
   2048 """
   2049 tg = TimeGrouper(obj, **kwds)  # type: ignore[arg-type]
-> 2050 return tg._get_resampler(obj, kind=kind)

File ~\anaconda3\Lib\site-packages\pandas\core\resample.py:2272, in TimeGrouper._get_resampler(self, obj, kind)
   2263 elif isinstance(ax, TimedeltaIndex):
   2264     return TimedeltaIndexResampler(
   2265         obj,
   2266         timegrouper=self,
   (...)
   2269         gpr_index=ax,
   2270     )
-> 2272 raise TypeError(
   2273     "Only valid with DatetimeIndex, "
   2274     "TimedeltaIndex or PeriodIndex, "
   2275     f"but got an instance of '{type(ax).__name__}'"
   2276 )

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'


how to solve this problem
