### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sunxin000** [salesforce/Merlion#82]
**Describe the bug**
when i run python benchmark_forecast.py --model ets --retrain_type sliding_window_retrain --n_retrain 4
retrain seems didnt work. the model is only trained once. 

i think that there is sometion wrong with the ForecastEvaluatorConfig.cadence, it is set to be the horizon, which is the lenth of the test_set, not the retrain_freq, so when one loop is done, t adding to the cadence larger then tf, the train procedure is over.

**Comment by aadyotb** [comment]
Thanks for pointing this out. PR #86 fixes the issue.
