### ISSUE TITLE
[FEATURE REQUEST] Options to impute missing values in univariate time series

### ISSUE THREAD

**Issue by darinkist** [salesforce/Merlion#83]
Imputing missing values with the _.algin()_ method works afaik only for multivariate (so a collection of univariate) time series. But what if I only have a single time series.

```python
from merlion.utils import TimeSeries
import pandas as pd
import numpy as np

ts_series = pd.Series(data = [20, 21, np.nan, 18],
                      index = ['01/04/2022', '02/04/2022', '03/04/2022', '04/04/2022'],
                      name = 'v'
                     )
ts_df = pd.DataFrame(ts_series)
ts_df.index = pd.to_datetime(ts_df.index)

ts = TimeSeries.from_pd(ts_df)
ts
```

In this case the entry for 03/04/2022 will be removed/excluded from the set when calling _.from_pd()_.
It would be great to still have here options to impute the nan value at index "03/04/2022".

What do you think?

**Comment by aadyotb** [comment]
Thanks for the question. This is a good point. PR #85 adds an option `drop_nan` to `TimeSeries.from_pd()` which allows you to keep the nan value and then impute it afterwards with `.align()`. Does this address your concern?
