### ISSUE TITLE
[BUG] Cannot install salesforce-merlion conda package in a python 3.9 environment on Mac

### ISSUE THREAD

**Issue by namaya** [salesforce/Merlion#84]
**Describe the bug**

The `salesforce-merlion` conda package is not installing in a python 3.9 environment. Instead, the following
error is being thrown

```
Encountered problems while solving:
  - package salesforce-merlion-1.0.0-pyhd8ed1ab_0 requires fbprophet, but none of the providers can be installed
```

**To Reproduce**

Create a python 3.9 environment and activate it

```
mamba create -n py39-env -c conda-forge 'python=3.9'
mamba activate py39-env
```

Install `salesforce-merlion` into environment

```
mamba install -c conda-forge salesforce-merlion
```

**Expected behavior**

`salesforce-merlion` conda package is installed and available in python environment.

**Screenshots**

<img width="828" alt="Screen Shot 2022-04-13 at 2 35 11 PM" src="https://user-images.githubusercontent.com/22106697/163257798-0b2338de-2255-4ae5-81c0-a431e8d370b3.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Merlion Version: 1.1.2

**Additional context**

These steps use `mamba` as it provides a clearer error message, but using `conda` directly doesn't work either. Also trying `mamba install -c conda-forge salesforce-merlion>=1.1.2` didn't help either.

**Comment by kgullikson88** [comment]
I think the main reason for this is that the [conda-forge feedstock](https://github.com/conda-forge/salesforce-merlion-feedstock/blob/main/recipe/meta.yaml#L25) still has merlion requiring the (old) `fbprophet` instead of the newer `prophet`. Probably just need to get those dependencies back in sync with what is in the setup.py here.

**Comment by aadyotb** [comment]
> I think the main reason for this is that the [conda-forge feedstock](https://github.com/conda-forge/salesforce-merlion-feedstock/blob/main/recipe/meta.yaml#L25) still has merlion requiring the (old) `fbprophet` instead of the newer `prophet`. Probably just need to get those dependencies back in sync with what is in the setup.py here.

Yeah, this sounds correct. @namaya I'm not the one maintaining the conda recipe, so I'd recommend taking this issue up with the maintainers of that repo.
