### ISSUE TITLE
[FEATURE REQUEST] Roadmap for Merlion

### ISSUE THREAD

**Issue by MBasalla** [salesforce/Merlion#95]
**Describe the solution you'd like**
It would be great to have a general roadmap of what is planned in the development of Merlion.

**Additional context**
One one hand it would help to decide if and how to integrate merlion in existing projects and work environments (e.g. which of the features, models, etc. we are missing right now are planned to be integrated into the library).
On the other hand it would help identify issues that are not on the main roadmap so that parties interested in these features can decide, whether to extend the current library for their usecase via forks of the repository or even pull requests.

**Comment by aadyotb** [comment]
Thanks for the question @MBasalla. We are hesitant to release an explicit roadmap at this time. However, I can tell you about three high priority features we are currently working on:

1. Deployment in a distributed computation environment using PySpark. This will include a containerized Docker app. The main goal of parallelism is to allow users to train models & run inference on multiple time series in parallel.
2. Support for forecasting with exogenous regressors. Specifically, we currently forecast `X_{t+1}, ..., X_{t+k}` conditioned on `X_1, ..., X_t`. Exogenous regressors add conditioning on `Y_1, ..., Y_t, Y_{t+1}, ..., Y_{t+k}` as well.
3. Improved support for deep learning models, as well as some new deep learning based forecasters.

I hope this helps. I'm also happy to discuss more specific feature requests with you and potentially guide you in the right direction towards implementing them.

**Comment by MBasalla** [comment]
Thank you for the quick response.

The general roadmap is a good indicator of what to expect in the future.

I agree that more specific separate feature requests are the best way to discuss more specific ideas and open issues.
