### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: 'java'

### ISSUE THREAD

**Issue by mccrinbc-ss** [salesforce/Merlion#96]
**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory: 'java'. Could this issue be related to VS Code, or did  OpenJDK not install correctly for Merlion's path dependencies?  

**To Reproduce**
Followed the steps to install _openjdk_ for Ubuntu using:
sudo apt-get install openjdk-11-jdk.

I loaded in my own proprietary dataset and followed the conversion steps:
```
train_data = TimeSeries.from_pd(private_data_df)
model.train(train_data=train_data)
```
This results in the following output:
![image](https://user-images.githubusercontent.com/83707037/171282780-afa16f55-417a-4a0e-bd17-d7b2e24bb2e1.png)

**Desktop (please complete the following information):**
 -  Linux pop-os 5.13.0-7620-generic Ubuntu x86_64 x86_64 x86_64 GNU/Linux
 - Merlion Version 1.1.3

**Comment by aadyotb** [comment]
I suspect you'll need to set the environment variable `$JAVA_HOME` appropriately, and ensure that `java`'s bin directory is on your `$PATH`.
